const connectDB = require("../config/db");
const Provider = require("../models/Provider");
const { logger } = require("../middlewares/logger");

const data = [
    {
      name: "Play'n GO",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1006,
      sort: 0,
      isAllowed: true,
      aliases: ["playngo", "play n go", "playn go", "png", "Play'n Go"],
      provider_code: "play_n_go",
    },
    {
      name: "Microgaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1007,
      sort: 0,
      isAllowed: true,
      aliases: ["mg", "micro", "micro gaming"],
      provider_code: "microgaming",
    },
    {
      name: "Quickspin",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1012,
      sort: 0,
      isAllowed: true,
      aliases: ["qs", "quick spin"],
      provider_code: "quickspin",
      autoEnableNewGames: true,
      maintenanceEndUTC: {
        $date: "2025-08-06T12:16:00.000Z",
      },
      maintenanceStartUTC: {
        $date: "2025-08-04T18:14:00.000Z",
      },
    },
    {
      name: "Wazdan",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1025,
      sort: 0,
      isAllowed: false,
      aliases: ["wzd", "wazdan gaming"],
      provider_code: "wazdan",
    },
    {
      name: "Iron Dog Studio",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1038,
      sort: 0,
      isAllowed: false,
      aliases: [
        "iron-dog-studio",
        "irondogstudio",
        "iron_dog_studio",
        "iron dog studio",
      ],
      provider_code: "iron_dog_studio",
    },
    {
      name: "Fantasma Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1064,
      sort: 0,
      isAllowed: false,
      aliases: [
        "fantasma-games",
        "fantasma games",
        "fantasma_games",
        "fantasmagames",
      ],
      provider_code: "fantasma_games",
    },
    {
      name: "CQ9 Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1069,
      sort: 0,
      isAllowed: false,
      aliases: ["cq9-gaming", "cq9_gaming", "cq9 gaming", "cq9gaming"],
      provider_code: "cq9_gaming",
    },
    {
      name: "WorldMatch",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1099,
      sort: 0,
      isAllowed: false,
      aliases: ["worldmatch"],
      provider_code: "worldmatch",
    },
    {
      name: "InOut Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1169,
      sort: 0,
      isAllowed: false,
      aliases: ["inoutgames", "inout-games", "inout_games", "inout games"],
      provider_code: "inout_games",
    },
    {
      name: "Nailed It! Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1186,
      sort: 0,
      isAllowed: false,
      aliases: [
        "nailed_it!_games",
        "nailedit!games",
        "nailed it! games",
        "nailed-it!-games",
      ],
      provider_code: "nailed_it_games",
    },
    {
      name: "Neon Valley Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1188,
      sort: 0,
      isAllowed: false,
      aliases: [
        "neon_valley_studios",
        "neonvalleystudios",
        "neon valley studios",
        "neon-valley-studios",
      ],
      provider_code: "neon_valley_studios",
    },
    {
      name: "NetGaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1190,
      sort: 0,
      isAllowed: false,
      aliases: ["netgaming"],
      provider_code: "netgaming",
    },
    {
      name: "Smartsoft Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1219,
      sort: 0,
      isAllowed: false,
      aliases: [
        "smartsoft_gaming",
        "smartsoftgaming",
        "smartsoft gaming",
        "smartsoft-gaming",
      ],
      provider_code: "smartsoft_gaming",
    },
    {
      name: "RubyPlay",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1250,
      sort: 0,
      isAllowed: false,
      aliases: ["rubyplay"],
      provider_code: "rubyplay",
    },
    {
      name: "POPOK",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1261,
      sort: 0,
      isAllowed: false,
      aliases: ["PopOk"],
      provider_code: "popok",
    },
    {
      name: "NetEnt",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1004,
      sort: 0,
      isAllowed: true,
      aliases: ["netent", "net", "net ent", "net-ent"],
      provider_code: "netent",
      autoEnableNewGames: true,
    },
    {
      name: "Authentic Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1014,
      sort: 0,
      isAllowed: true,
      aliases: [
        "authentic gaming",
        "authentic-gaming",
        "authentic_gaming",
        "authenticgaming",
      ],
      provider_code: "authentic_gaming",
    },
    {
      name: "ReelPlay",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1046,
      sort: 0,
      isAllowed: false,
      aliases: ["reelplay"],
      provider_code: "reelplay",
    },
    {
      name: "Maverick Slots",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1079,
      sort: 0,
      isAllowed: false,
      aliases: [
        "maverickslots",
        "maverick-slots",
        "maverick_slots",
        "maverick slots",
      ],
      provider_code: "maverick_slots",
    },
    {
      name: "InBet Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1094,
      sort: 0,
      isAllowed: false,
      aliases: ["inbet-games", "inbet_games", "inbetgames", "inbet games"],
      provider_code: "inbet_games",
    },
    {
      name: "Jili Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1102,
      sort: 0,
      isAllowed: false,
      aliases: ["JiLi Gaming"],
      provider_code: "jili_gaming",
    },
    {
      name: "Buck Stakes Entertainment",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1133,
      sort: 0,
      isAllowed: false,
      aliases: [
        "buck-stakes-entertainment",
        "buck_stakes_entertainment",
        "buck stakes entertainment",
        "buckstakesentertainment",
      ],
      provider_code: "buck_stakes_entertainment",
    },
    {
      name: "Charismatic",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1137,
      sort: 0,
      isAllowed: false,
      aliases: ["charismatic"],
      provider_code: "charismatic",
    },
    {
      name: "Evoplay Entertainment",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1145,
      sort: 0,
      isAllowed: false,
      aliases: [
        "evoplay entertainment",
        "evoplayentertainment",
        "evoplay_entertainment",
        "evoplay-entertainment",
      ],
      provider_code: "evoplay_entertainment",
    },
    {
      name: "Gameburger Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1154,
      sort: 0,
      isAllowed: false,
      aliases: [
        "gameburger_studios",
        "gameburger-studios",
        "gameburger studios",
        "gameburgerstudios",
      ],
      provider_code: "gameburger_studios",
    },
    {
      name: "Kingmidas",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1175,
      sort: 0,
      isAllowed: false,
      aliases: ["kingmidas"],
      provider_code: "kingmidas",
    },
    {
      name: "Kiron Interactive",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1176,
      sort: 0,
      isAllowed: false,
      aliases: [
        "kironinteractive",
        "kiron-interactive",
        "kiron interactive",
        "kiron_interactive",
      ],
      provider_code: "kiron_interactive",
    },
    {
      name: "MegaFUNalo",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1182,
      sort: 0,
      isAllowed: false,
      aliases: ["megafunalo"],
      provider_code: "megafunalo",
    },
    {
      name: "PHOENIX 7",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1199,
      sort: 0,
      isAllowed: false,
      aliases: ["phoenix7", "phoenix_7", "phoenix 7", "phoenix-7"],
      provider_code: "phoenix_7",
    },
    {
      name: "MARBLES",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1254,
      sort: 0,
      isAllowed: false,
      aliases: ["Marbles"],
      provider_code: "marbles",
    },
    {
      name: "HORSEBOOK",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1259,
      sort: 0,
      isAllowed: false,
      aliases: ["horsebook"],
      provider_code: "horsebook",
    },
    {
      name: "Blueprint Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1023,
      sort: 0,
      isAllowed: false,
      aliases: ["blueprint", "bpg"],
      provider_code: "blueprint_gaming",
      autoEnableNewGames: false,
      maintenanceEndUTC: null,
      maintenanceStartUTC: null,
    },
    {
      name: "Spinomenal",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1027,
      sort: 0,
      isAllowed: true,
      aliases: ["spinomenal"],
      provider_code: "spinomenal",
      autoEnableNewGames: true,
    },
    {
      name: "SoftSwiss (BGaming)",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1028,
      sort: 0,
      isAllowed: false,
      aliases: [
        "softswiss_bgaming",
        "softswiss-bgaming",
        "softswiss (bgaming)",
        "softswissbgaming",
      ],
      provider_code: "softswiss_bgaming",
    },
    {
      name: "Casino Technology",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1068,
      sort: 0,
      isAllowed: false,
      aliases: [
        "casinotechnology",
        "casino technology",
        "casino-technology",
        "casino_technology",
      ],
      provider_code: "casino_technology",
    },
    {
      name: "Pearl Abyss",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1077,
      sort: 0,
      isAllowed: false,
      aliases: ["pearlabyss", "pearl-abyss", "pearl_abyss", "pearl abyss"],
      provider_code: "pearl_abyss",
    },
    {
      name: "Real Dealer Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1080,
      sort: 0,
      isAllowed: false,
      aliases: [
        "real dealer studios",
        "realdealerstudios",
        "real_dealer_studios",
        "real-dealer-studios",
      ],
      provider_code: "real_dealer_studios",
    },
    {
      name: "Onlyplay",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1088,
      sort: 0,
      isAllowed: false,
      aliases: ["onlyplay"],
      provider_code: "onlyplay",
    },
    {
      name: "BGaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1095,
      sort: 0,
      isAllowed: false,
      aliases: ["bgaming"],
      provider_code: "bgaming",
    },
    {
      name: "KA Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1096,
      sort: 0,
      isAllowed: false,
      aliases: ["ka_gaming", "kagaming", "ka-gaming", "ka gaming"],
      provider_code: "ka_gaming",
    },
    {
      name: "Aurum Signature Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1117,
      sort: 0,
      isAllowed: false,
      aliases: [
        "aurum signature studios",
        "aurum_signature_studios",
        "aurum-signature-studios",
        "aurumsignaturestudios",
      ],
      provider_code: "aurum_signature_studios",
    },
    {
      name: "Barstruck",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1126,
      sort: 0,
      isAllowed: false,
      aliases: ["barstruck"],
      provider_code: "barstruck",
    },
    {
      name: "Gaming Realms",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1157,
      sort: 0,
      isAllowed: false,
      aliases: [
        "gaming-realms",
        "gaming realms",
        "gaming_realms",
        "gamingrealms",
      ],
      provider_code: "gaming_realms",
    },
    {
      name: "Gong Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1160,
      sort: 0,
      isAllowed: false,
      aliases: ["gong_gaming", "gong gaming", "gonggaming", "gong-gaming"],
      provider_code: "gong_gaming",
    },
    {
      name: "Kitsune Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1177,
      sort: 0,
      isAllowed: false,
      aliases: [
        "kitsune_studios",
        "kitsunestudios",
        "kitsune-studios",
        "kitsune studios",
      ],
      provider_code: "kitsune_studios",
    },
    {
      name: "Reevo",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1211,
      sort: 0,
      isAllowed: false,
      aliases: ["reevo"],
      provider_code: "reevo",
    },
    {
      name: "TVBet",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1228,
      sort: 0,
      isAllowed: false,
      aliases: ["TVBET", "tvbet"],
      provider_code: "tvbet",
    },
    {
      name: "Win Fast Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1237,
      sort: 0,
      isAllowed: false,
      aliases: [
        "win fast games",
        "winfastgames",
        "win-fast-games",
        "win_fast_games",
      ],
      provider_code: "win_fast_games",
    },
    {
      name: "Evolution Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1244,
      sort: 0,
      isAllowed: false,
      aliases: ["Evolution"],
      provider_code: "evolution_gaming",
      autoEnableNewGames: false,
      maintenanceEndUTC: {
        $date: "2025-08-04T20:00:00.000Z",
      },
      maintenanceStartUTC: {
        $date: "2025-07-30T20:00:00.000Z",
      },
    },
    {
      name: "Habanero",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1246,
      sort: 0,
      isAllowed: false,
      aliases: ["habanero"],
      provider_code: "habanero",
      autoEnableNewGames: false,
      maintenanceEndUTC: {
        $date: "2025-08-12T20:00:00.000Z",
      },
      maintenanceStartUTC: {
        $date: "2025-08-06T11:16:00.000Z",
      },
    },
    {
      name: "Yggdrasil",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1009,
      sort: 0,
      isAllowed: true,
      aliases: ["ygg", "yggdrasil gaming"],
      provider_code: "yggdrasil",
      autoEnableNewGames: true,
    },
    {
      name: "NoLimit City",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1021,
      sort: 0,
      isAllowed: false,
      aliases: ["nolimit", "nlc"],
      provider_code: "nolimit_city",
    },
    {
      name: "Playson",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1031,
      sort: 0,
      isAllowed: false,
      aliases: ["playson"],
      provider_code: "playson",
    },
    {
      name: "Leap Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1056,
      sort: 0,
      isAllowed: false,
      aliases: ["leap_gaming", "leap-gaming", "leapgaming", "leap gaming"],
      provider_code: "leap_gaming",
    },
    {
      name: "Spinmatic",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1059,
      sort: 0,
      isAllowed: false,
      aliases: ["spinmatic"],
      provider_code: "spinmatic",
    },
    {
      name: "Wizard Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1061,
      sort: 0,
      isAllowed: false,
      aliases: ["wizardgames", "wizard games", "wizard-games", "wizard_games"],
      provider_code: "wizard_games",
    },
    {
      name: "7Mojos",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1066,
      sort: 0,
      isAllowed: false,
      aliases: ["7mojos"],
      provider_code: "7mojos",
    },
    {
      name: "Jelly",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1173,
      sort: 0,
      isAllowed: false,
      aliases: ["jelly"],
      provider_code: "jelly",
    },
    {
      name: "Neko Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1187,
      sort: 0,
      isAllowed: false,
      aliases: ["neko_games", "neko-games", "nekogames", "neko games"],
      provider_code: "neko_games",
    },
    {
      name: "Winfinity",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1238,
      sort: 0,
      isAllowed: false,
      aliases: ["winfinity"],
      provider_code: "winfinity",
    },
    {
      name: "Yolted",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1242,
      sort: 0,
      isAllowed: false,
      aliases: ["yolted"],
      provider_code: "yolted",
    },
    {
      name: "PGSoft",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1249,
      sort: 0,
      isAllowed: false,
      aliases: ["pgsoft"],
      provider_code: "pgsoft",
    },
    {
      name: "Royal Gaming Virtual",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1263,
      sort: 0,
      isAllowed: false,
      aliases: [
        "royal-gaming-virtual",
        "royal gaming virtual",
        "royalgamingvirtual",
        "royal_gaming_virtual",
      ],
      provider_code: "royal_gaming_virtual",
    },
    {
      name: "Big Time Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1011,
      sort: 0,
      isAllowed: true,
      aliases: [
        "big time gaming",
        "bigtimegaming",
        "big_time_gaming",
        "big-time-gaming",
      ],
      provider_code: "big_time_gaming",
    },
    {
      name: "OnAir Entertainment",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1015,
      sort: 0,
      isAllowed: false,
      aliases: [
        "onair_entertainment",
        "onair-entertainment",
        "onair entertainment",
        "onairentertainment",
      ],
      provider_code: "onair_entertainment",
    },
    {
      name: "Relax Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1020,
      sort: 0,
      isAllowed: true,
      aliases: ["relax", "relaxgaming"],
      provider_code: "relax_gaming",
      autoEnableNewGames: true,
    },
    {
      name: "1x2gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1037,
      sort: 0,
      isAllowed: false,
      aliases: ["1x2gaming"],
      provider_code: "1x2gaming",
    },
    {
      name: "BetGames",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1049,
      sort: 0,
      isAllowed: false,
      aliases: ["BETGAMES"],
      provider_code: "betgames",
    },
    {
      name: "Red Rake Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1070,
      sort: 0,
      isAllowed: false,
      aliases: [
        "red rake gaming",
        "red-rake-gaming",
        "red_rake_gaming",
        "redrakegaming",
      ],
      provider_code: "red_rake_gaming",
    },
    {
      name: "Boomerang Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1131,
      sort: 0,
      isAllowed: false,
      aliases: ["Boomerang"],
      provider_code: "boomerang_studios",
    },
    {
      name: "Bulletproof Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1134,
      sort: 0,
      isAllowed: false,
      aliases: [
        "bulletproof games",
        "bulletproof-games",
        "bulletproofgames",
        "bulletproof_games",
      ],
      provider_code: "bulletproof_games",
    },
    {
      name: "SpinOro",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1221,
      sort: 0,
      isAllowed: false,
      aliases: ["spinoro"],
      provider_code: "spinoro",
    },
    {
      name: "SpinPlay Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1222,
      sort: 0,
      isAllowed: false,
      aliases: [
        "spinplaygames",
        "spinplay games",
        "spinplay-games",
        "spinplay_games",
      ],
      provider_code: "spinplay_games",
    },
    {
      name: "Kalamba Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1026,
      sort: 0,
      isAllowed: false,
      aliases: [
        "kalamba-games",
        "kalambagames",
        "kalamba games",
        "kalamba_games",
      ],
      provider_code: "kalamba_games",
    },
    {
      name: "Mascot Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1036,
      sort: 0,
      isAllowed: false,
      aliases: [
        "mascot gaming",
        "mascot_gaming",
        "mascot-gaming",
        "mascotgaming",
      ],
      provider_code: "mascot_gaming",
    },
    {
      name: "Spearhead Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1053,
      sort: 0,
      isAllowed: false,
      aliases: [
        "spearhead_studios",
        "spearhead studios",
        "spearheadstudios",
        "spearhead-studios",
      ],
      provider_code: "spearhead_studios",
    },
    {
      name: "All41 Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1054,
      sort: 0,
      isAllowed: false,
      aliases: [
        "all41-studios",
        "all41_studios",
        "all41studios",
        "all41 studios",
      ],
      provider_code: "all41_studios",
    },
    {
      name: "Green Jade Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1057,
      sort: 0,
      isAllowed: false,
      aliases: [
        "green_jade_games",
        "green jade games",
        "greenjadegames",
        "green-jade-games",
      ],
      provider_code: "green_jade_games",
    },
    {
      name: "August Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1065,
      sort: 0,
      isAllowed: false,
      aliases: [
        "august gaming",
        "augustgaming",
        "august-gaming",
        "august_gaming",
      ],
      provider_code: "august_gaming",
    },
    {
      name: "Slingshot Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1072,
      sort: 0,
      isAllowed: false,
      aliases: [
        "slingshot-studios",
        "slingshot_studios",
        "slingshot studios",
        "slingshotstudios",
      ],
      provider_code: "slingshot_studios",
    },
    {
      name: "Just For The Win (JFTW)",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1074,
      sort: 0,
      isAllowed: false,
      aliases: [
        "just_for_the_win_jftw",
        "justforthewinjftw",
        "just for the win (jftw)",
        "just-for-the-win-jftw",
      ],
      provider_code: "just_for_the_win_jftw",
    },
    {
      name: "Synot Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1085,
      sort: 0,
      isAllowed: false,
      aliases: ["synot-games", "synot games", "synotgames", "synot_games"],
      provider_code: "synot_games",
    },
    {
      name: "Ace Roll",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1110,
      sort: 0,
      isAllowed: false,
      aliases: ["ace_roll", "ace roll", "ace-roll", "aceroll"],
      provider_code: "ace_roll",
    },
    {
      name: "Jade Rabbit Studio",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1172,
      sort: 0,
      isAllowed: false,
      aliases: [
        "jade-rabbit-studio",
        "jade rabbit studio",
        "jade_rabbit_studio",
        "jaderabbitstudio",
      ],
      provider_code: "jade_rabbit_studio",
    },
    {
      name: "Just For The Win Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1174,
      sort: 0,
      isAllowed: false,
      aliases: [
        "just for the win studios",
        "just_for_the_win_studios",
        "just-for-the-win-studios",
        "justforthewinstudios",
      ],
      provider_code: "just_for_the_win_studios",
    },
    {
      name: "Leander Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1179,
      sort: 0,
      isAllowed: false,
      aliases: [
        "leander-games",
        "leandergames",
        "leander games",
        "leander_games",
      ],
      provider_code: "leander_games",
    },
    {
      name: "Rabcat Gambling",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1207,
      sort: 0,
      isAllowed: false,
      aliases: ["Rabcat"],
      provider_code: "rabcat_gambling",
    },
    {
      name: "Sap",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1216,
      sort: 0,
      isAllowed: false,
      aliases: ["sap"],
      provider_code: "sap",
    },
    {
      name: "Shady Lady",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1217,
      sort: 0,
      isAllowed: false,
      aliases: ["shady_lady", "shadylady", "shady lady", "shady-lady"],
      provider_code: "shady_lady",
    },
    {
      name: "Top Spin",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1231,
      sort: 0,
      isAllowed: false,
      aliases: ["topspin", "top-spin", "top spin", "top_spin"],
      provider_code: "top_spin",
    },
    {
      name: "Playtech Live",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1248,
      sort: 0,
      isAllowed: false,
      aliases: [
        "playtech_live",
        "playtechlive",
        "playtech-live",
        "playtech live",
      ],
      provider_code: "playtech_live",
    },
    {
      name: "Red Tiger",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1010,
      sort: 0,
      isAllowed: true,
      aliases: ["redtiger", "red tiger gaming"],
      provider_code: "red_tiger",
      autoEnableNewGames: true,
      maintenanceEndUTC: {
        $date: "2025-08-15T20:00:00.000Z",
      },
      maintenanceStartUTC: {
        $date: "2025-08-14T20:00:00.000Z",
      },
    },
    {
      name: "Pariplay",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1032,
      sort: 0,
      isAllowed: false,
      aliases: ["pariplay"],
      provider_code: "pariplay",
    },
    {
      name: "Belatra Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1035,
      sort: 0,
      isAllowed: false,
      aliases: [
        "belatragames",
        "belatra games",
        "belatra_games",
        "belatra-games",
      ],
      provider_code: "belatra_games",
    },
    {
      name: "LuckyStreak",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1048,
      sort: 0,
      isAllowed: false,
      aliases: ["luckystreak"],
      provider_code: "luckystreak",
    },
    {
      name: "Alchemy Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1112,
      sort: 0,
      isAllowed: false,
      aliases: [
        "alchemygaming",
        "alchemy_gaming",
        "alchemy-gaming",
        "alchemy gaming",
      ],
      provider_code: "alchemy_gaming",
    },
    {
      name: "Aviator",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1119,
      sort: 0,
      isAllowed: false,
      aliases: ["aviator"],
      provider_code: "aviator",
    },
    {
      name: "Elysium Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1142,
      sort: 0,
      isAllowed: false,
      aliases: [
        "elysium-studios",
        "elysium studios",
        "elysiumstudios",
        "elysium_studios",
      ],
      provider_code: "elysium_studios",
    },
    {
      name: "Eurostar Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1144,
      sort: 0,
      isAllowed: false,
      aliases: [
        "eurostar-studios",
        "eurostar studios",
        "eurostar_studios",
        "eurostarstudios",
      ],
      provider_code: "eurostar_studios",
    },
    {
      name: "Fortune Factory Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1148,
      sort: 0,
      isAllowed: false,
      aliases: [
        "fortune_factory_studios",
        "fortunefactorystudios",
        "fortune factory studios",
        "fortune-factory-studios",
      ],
      provider_code: "fortune_factory_studios",
    },
    {
      name: "Gacha Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1150,
      sort: 0,
      isAllowed: false,
      aliases: [
        "gacha_studios",
        "gachastudios",
        "gacha-studios",
        "gacha studios",
      ],
      provider_code: "gacha_studios",
    },
    {
      name: "Games Global",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1155,
      sort: 0,
      isAllowed: false,
      aliases: ["games global", "gamesglobal", "games_global", "games-global"],
      provider_code: "games_global",
    },
    {
      name: "Half Pixel Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1161,
      sort: 0,
      isAllowed: false,
      aliases: [
        "half-pixel-studios",
        "half pixel studios",
        "halfpixelstudios",
        "half_pixel_studios",
      ],
      provider_code: "half_pixel_studios",
    },
    {
      name: "ICONIC21",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1167,
      sort: 0,
      isAllowed: false,
      aliases: ["iconic21"],
      provider_code: "iconic21",
    },
    {
      name: "Playtech",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1247,
      sort: 0,
      isAllowed: false,
      aliases: ["playtech"],
      provider_code: "playtech",
    },
    {
      name: "Fugaso",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1040,
      sort: 0,
      isAllowed: false,
      aliases: ["fugaso"],
      provider_code: "fugaso",
    },
    {
      name: "Lightning Box",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1075,
      sort: 0,
      isAllowed: false,
      aliases: [
        "lightning-box",
        "lightningbox",
        "lightning_box",
        "lightning box",
      ],
      provider_code: "lightning_box",
    },
    {
      name: "SmartSoft Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1081,
      sort: 0,
      isAllowed: false,
      aliases: [
        "smartsoft_gaming",
        "smartsoftgaming",
        "smartsoft gaming",
        "smartsoft-gaming",
      ],
      provider_code: "smartsoft_gaming",
    },
    {
      name: "Arcadem",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1087,
      sort: 0,
      isAllowed: false,
      aliases: ["arcadem"],
      provider_code: "arcadem",
    },
    {
      name: "Nucleus Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1098,
      sort: 0,
      isAllowed: false,
      aliases: [
        "nucleusgaming",
        "nucleus-gaming",
        "nucleus gaming",
        "nucleus_gaming",
      ],
      provider_code: "nucleus_gaming",
    },
    {
      name: "CT Interactive",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1103,
      sort: 0,
      isAllowed: false,
      aliases: [
        "ct interactive",
        "ct_interactive",
        "ctinteractive",
        "ct-interactive",
      ],
      provider_code: "ct_interactive",
    },
    {
      name: "Aura Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1116,
      sort: 0,
      isAllowed: false,
      aliases: ["auragaming", "aura gaming", "aura-gaming", "aura_gaming"],
      provider_code: "aura_gaming",
    },
    {
      name: "Circular Arrow",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1138,
      sort: 0,
      isAllowed: false,
      aliases: [
        "circular-arrow",
        "circular arrow",
        "circular_arrow",
        "circulararrow",
      ],
      provider_code: "circular_arrow",
    },
    {
      name: "Infinity Dragon Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1170,
      sort: 0,
      isAllowed: false,
      aliases: [
        "infinity dragon studios",
        "infinitydragonstudios",
        "infinity_dragon_studios",
        "infinity-dragon-studios",
      ],
      provider_code: "infinity_dragon_studios",
    },
    {
      name: "JDB",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1171,
      sort: 0,
      isAllowed: false,
      aliases: ["jdb"],
      provider_code: "jdb",
    },
    {
      name: "Switch Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1227,
      sort: 0,
      isAllowed: false,
      aliases: [
        "switch studios",
        "switchstudios",
        "switch_studios",
        "switch-studios",
      ],
      provider_code: "switch_studios",
    },
    {
      name: "Winspinity",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1239,
      sort: 0,
      isAllowed: false,
      aliases: ["winspinity"],
      provider_code: "winspinity",
    },
    {
      name: "Wishbone",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1240,
      sort: 0,
      isAllowed: false,
      aliases: ["wishbone"],
      provider_code: "wishbone",
    },
    {
      name: "CREED",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1262,
      sort: 0,
      isAllowed: false,
      aliases: ["creed"],
      provider_code: "creed",
    },
    {
      name: "Tom Horn Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1041,
      sort: 0,
      isAllowed: false,
      aliases: [
        "tomhorngaming",
        "tom_horn_gaming",
        "tom-horn-gaming",
        "tom horn gaming",
      ],
      provider_code: "tom_horn_gaming",
    },
    {
      name: "Peter & Sons",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1044,
      sort: 0,
      isAllowed: false,
      aliases: [
        "peterandsons",
        "peter-and-sons",
        "peter_and_sons",
        "peter & sons",
      ],
      provider_code: "peter_sons",
    },
    {
      name: "OneTouch",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1082,
      sort: 0,
      isAllowed: false,
      aliases: ["onetouch"],
      provider_code: "onetouch",
    },
    {
      name: "Spribe",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1089,
      sort: 0,
      isAllowed: false,
      aliases: ["SPRIBE"],
      provider_code: "spribe",
    },
    {
      name: "1Spin4Win",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1105,
      sort: 0,
      isAllowed: false,
      aliases: ["1spin4win"],
      provider_code: "1spin4win",
    },
    {
      name: "9 Wickets",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1108,
      sort: 0,
      isAllowed: false,
      aliases: ["9_wickets", "9wickets", "9-wickets", "9 wickets"],
      provider_code: "9_wickets",
    },
    {
      name: "All For One Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1113,
      sort: 0,
      isAllowed: false,
      aliases: [
        "allforonestudios",
        "all-for-one-studios",
        "all_for_one_studios",
        "all for one studios",
      ],
      provider_code: "all_for_one_studios",
    },
    {
      name: "Amigo Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1114,
      sort: 0,
      isAllowed: false,
      aliases: ["amigo-gaming", "amigogaming", "amigo gaming", "amigo_gaming"],
      provider_code: "amigo_gaming",
    },
    {
      name: "Aviatrix",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1120,
      sort: 0,
      isAllowed: false,
      aliases: ["aviatrix"],
      provider_code: "aviatrix",
    },
    {
      name: "BTi",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1121,
      sort: 0,
      isAllowed: false,
      aliases: ["bti"],
      provider_code: "bti",
    },
    {
      name: "Bullshark Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1135,
      sort: 0,
      isAllowed: false,
      aliases: [
        "bullshark games",
        "bullsharkgames",
        "bullshark_games",
        "bullshark-games",
      ],
      provider_code: "bullshark_games",
    },
    {
      name: "Crazy Tooth Studio",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1140,
      sort: 0,
      isAllowed: false,
      aliases: [
        "crazy tooth studio",
        "crazy-tooth-studio",
        "crazytoothstudio",
        "crazy_tooth_studio",
      ],
      provider_code: "crazy_tooth_studio",
    },
    {
      name: "Fa Chai",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1146,
      sort: 0,
      isAllowed: false,
      aliases: ["fa-chai", "fa_chai", "fa chai", "fachai"],
      provider_code: "fa_chai",
    },
    {
      name: "Gambit",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1151,
      sort: 0,
      isAllowed: false,
      aliases: ["gambit"],
      provider_code: "gambit",
    },
    {
      name: "INO Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1168,
      sort: 0,
      isAllowed: false,
      aliases: ["inogames", "ino_games", "ino-games", "ino games"],
      provider_code: "ino_games",
    },
    {
      name: "Octoplay",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1194,
      sort: 0,
      isAllowed: false,
      aliases: ["octoplay"],
      provider_code: "octoplay",
    },
    {
      name: "Royal Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1213,
      sort: 0,
      isAllowed: false,
      aliases: ["royal_gaming", "royal gaming", "royalgaming", "royal-gaming"],
      provider_code: "royal_gaming",
    },
    {
      name: "Snowborn Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1220,
      sort: 0,
      isAllowed: false,
      aliases: [
        "snowborn_games",
        "snowborn-games",
        "snowborn games",
        "snowborngames",
      ],
      provider_code: "snowborn_games",
    },
    {
      name: "Pragmatic Play",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1005,
      sort: 0,
      isAllowed: true,
      aliases: [
        "PG",
        "pragmatic",
        "pragmatic play",
        "pragmaticplay",
        "pragmatic_play",
      ],
      provider_code: "pragmatic_play",
    },
    {
      name: "Hacksaw Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1018,
      sort: 0,
      isAllowed: false,
      aliases: [
        "hacksawgaming",
        "hacksaw-gaming",
        "hacksaw_gaming",
        "hacksaw gaming",
      ],
      provider_code: "hacksaw_gaming",
      autoEnableNewGames: true,
    },
    {
      name: "Push Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1019,
      sort: 0,
      isAllowed: false,
      aliases: ["push", "pushgaming"],
      provider_code: "push_gaming",
    },
    {
      name: "Skywind Group",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1060,
      sort: 0,
      isAllowed: false,
      aliases: [
        "skywind group",
        "skywind_group",
        "skywindgroup",
        "skywind-group",
      ],
      provider_code: "skywind_group",
    },
    {
      name: "Betixon",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1067,
      sort: 0,
      isAllowed: false,
      aliases: ["betixon"],
      provider_code: "betixon",
    },
    {
      name: "BetGames Live",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1127,
      sort: 0,
      isAllowed: false,
      aliases: [
        "betgames-live",
        "betgameslive",
        "betgames_live",
        "betgames live",
      ],
      provider_code: "betgames_live",
    },
    {
      name: "Gaming Corps",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1156,
      sort: 0,
      isAllowed: false,
      aliases: ["gaming corps", "gamingcorps", "gaming-corps", "gaming_corps"],
      provider_code: "gaming_corps",
    },
    {
      name: "High Limit Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1163,
      sort: 0,
      isAllowed: false,
      aliases: [
        "high limit studios",
        "high_limit_studios",
        "highlimitstudios",
        "high-limit-studios",
      ],
      provider_code: "high_limit_studios",
    },
    {
      name: "Lambda Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1178,
      sort: 0,
      isAllowed: false,
      aliases: [
        "lambda-gaming",
        "lambdagaming",
        "lambda_gaming",
        "lambda gaming",
      ],
      provider_code: "lambda_gaming",
    },
    {
      name: "Manna Play",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1181,
      sort: 0,
      isAllowed: false,
      aliases: ["manna-play", "mannaplay", "manna play", "manna_play"],
      provider_code: "manna_play",
    },
    {
      name: "Mobilots",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1184,
      sort: 0,
      isAllowed: false,
      aliases: ["mobilots"],
      provider_code: "mobilots",
    },
    {
      name: "NetGame Entertainment",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1189,
      sort: 0,
      isAllowed: false,
      aliases: [
        "netgame_entertainment",
        "netgame entertainment",
        "netgameentertainment",
        "netgame-entertainment",
      ],
      provider_code: "netgame_entertainment",
    },
    {
      name: "Oros Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1198,
      sort: 0,
      isAllowed: false,
      aliases: ["oros gaming", "oros_gaming", "orosgaming", "oros-gaming"],
      provider_code: "oros_gaming",
    },
    {
      name: "RTG Slots",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1206,
      sort: 0,
      isAllowed: false,
      aliases: ["rtg_slots", "rtgslots", "rtg-slots", "rtg slots"],
      provider_code: "rtg_slots",
    },
    {
      name: "SA Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1214,
      sort: 0,
      isAllowed: false,
      aliases: ["sa gaming", "sa-gaming", "sa_gaming", "sagaming"],
      provider_code: "sa_gaming",
    },
    {
      name: "Swintt Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1225,
      sort: 0,
      isAllowed: false,
      aliases: ["swinttgames", "swintt_games", "swintt-games", "swintt games"],
      provider_code: "swintt_games",
    },
    {
      name: "Swintt Premium",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1226,
      sort: 0,
      isAllowed: false,
      aliases: [
        "swinttpremium",
        "swintt-premium",
        "swintt_premium",
        "swintt premium",
      ],
      provider_code: "swintt_premium",
    },
    {
      name: "Tequity Originals",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1230,
      sort: 0,
      isAllowed: false,
      aliases: [
        "tequity_originals",
        "tequityoriginals",
        "tequity originals",
        "tequity-originals",
      ],
      provider_code: "tequity_originals",
    },
    {
      name: "Trusty Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1232,
      sort: 0,
      isAllowed: false,
      aliases: [
        "trusty-studios",
        "trusty studios",
        "trustystudios",
        "trusty_studios",
      ],
      provider_code: "trusty_studios",
    },
    {
      name: "Yellow Bat Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1241,
      sort: 0,
      isAllowed: false,
      aliases: [
        "yellow bat gaming",
        "yellowbatgaming",
        "yellow-bat-gaming",
        "yellow_bat_gaming",
      ],
      provider_code: "yellow_bat_gaming",
    },
    {
      name: "Vivo Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1016,
      sort: 0,
      isAllowed: false,
      aliases: ["Vivo Games"],
      provider_code: "vivo_gaming",
    },
    {
      name: "Digitain",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1051,
      sort: 0,
      isAllowed: false,
      aliases: ["digitain"],
      provider_code: "digitain",
    },
    {
      name: "BF Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1062,
      sort: 0,
      isAllowed: false,
      aliases: ["bfgames", "bf-games", "bf games", "bf_games"],
      provider_code: "bf_games",
    },
    {
      name: "Games Inc",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1084,
      sort: 0,
      isAllowed: false,
      aliases: ["games_inc", "games inc", "gamesinc", "games-inc"],
      provider_code: "games_inc",
    },
    {
      name: "Lucky Elektra",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1093,
      sort: 0,
      isAllowed: false,
      aliases: [
        "lucky-elektra",
        "luckyelektra",
        "lucky_elektra",
        "lucky elektra",
      ],
      provider_code: "lucky_elektra",
    },
    {
      name: "Bad Dingo",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1123,
      sort: 0,
      isAllowed: false,
      aliases: ["bad_dingo", "bad dingo", "baddingo", "bad-dingo"],
      provider_code: "bad_dingo",
    },
    {
      name: "Blue Ring Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1130,
      sort: 0,
      isAllowed: false,
      aliases: [
        "blueringstudios",
        "blue-ring-studios",
        "blue ring studios",
        "blue_ring_studios",
      ],
      provider_code: "blue_ring_studios",
    },
    {
      name: "Hammertime Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1162,
      sort: 0,
      isAllowed: false,
      aliases: [
        "hammertime-games",
        "hammertime_games",
        "hammertimegames",
        "hammertime games",
      ],
      provider_code: "hammertime_games",
    },
    {
      name: "OneGame",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1196,
      sort: 0,
      isAllowed: false,
      aliases: ["onegame"],
      provider_code: "onegame",
    },
    {
      name: "Playzia",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1202,
      sort: 0,
      isAllowed: false,
      aliases: ["playzia"],
      provider_code: "playzia",
    },
    {
      name: "Popiplay",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1203,
      sort: 0,
      isAllowed: false,
      aliases: ["popiplay"],
      provider_code: "popiplay",
    },
    {
      name: "Print Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1204,
      sort: 0,
      isAllowed: false,
      aliases: [
        "print studios",
        "print-studios",
        "printstudios",
        "print_studios",
      ],
      provider_code: "print_studios",
    },
    {
      name: "Qubit Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1205,
      sort: 0,
      isAllowed: false,
      aliases: ["qubit-games", "qubit_games", "qubitgames", "qubit games"],
      provider_code: "qubit_games",
    },
    {
      name: "Saba Sports",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1215,
      sort: 0,
      isAllowed: false,
      aliases: ["SABA"],
      provider_code: "saba_sports",
    },
    {
      name: "TaDa Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1229,
      sort: 0,
      isAllowed: false,
      aliases: ["tada-gaming", "tadagaming", "tada gaming", "tada_gaming"],
      provider_code: "tada_gaming",
    },
    {
      name: "Wicked Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1236,
      sort: 0,
      isAllowed: false,
      aliases: ["wicked games", "wickedgames", "wicked_games", "wicked-games"],
      provider_code: "wicked_games",
    },
    {
      name: "Ezugi",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1013,
      sort: 0,
      isAllowed: true,
      aliases: ["ezg", "ez"],
      provider_code: "ezugi",
      autoEnableNewGames: false,
    },
    {
      name: "Asia Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1017,
      sort: 0,
      isAllowed: false,
      aliases: ["asia gaming", "asia_gaming", "asia-gaming", "asiagaming"],
      provider_code: "asia_gaming",
    },
    {
      name: "Thunderkick",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1024,
      sort: 0,
      isAllowed: false,
      aliases: ["tk", "thunder kick"],
      provider_code: "thunderkick",
    },
    {
      name: "Amatic Industries",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1029,
      sort: 0,
      isAllowed: false,
      aliases: [
        "amatic_industries",
        "amaticindustries",
        "amatic-industries",
        "amatic industries",
      ],
      provider_code: "amatic_industries",
    },
    {
      name: "Booming Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1034,
      sort: 0,
      isAllowed: false,
      aliases: [
        "booming_games",
        "boominggames",
        "booming games",
        "booming-games",
      ],
      provider_code: "booming_games",
    },
    {
      name: "Slotmill",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1043,
      sort: 0,
      isAllowed: false,
      aliases: ["slotmill"],
      provider_code: "slotmill",
    },
    {
      name: "Stormcraft Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1047,
      sort: 0,
      isAllowed: false,
      aliases: [
        "stormcraft studios",
        "stormcraftstudios",
        "stormcraft-studios",
        "stormcraft_studios",
      ],
      provider_code: "stormcraft_studios",
    },
    {
      name: "Givme Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1063,
      sort: 0,
      isAllowed: false,
      aliases: ["givmegames", "givme games", "givme-games", "givme_games"],
      provider_code: "givme_games",
    },
    {
      name: "PearFiction Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1076,
      sort: 0,
      isAllowed: false,
      aliases: [
        "pearfictionstudios",
        "pearfiction studios",
        "pearfiction-studios",
        "pearfiction_studios",
      ],
      provider_code: "pearfiction_studios",
    },
    {
      name: "EvenBet Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1100,
      sort: 0,
      isAllowed: false,
      aliases: [
        "evenbet_gaming",
        "evenbet gaming",
        "evenbet-gaming",
        "evenbetgaming",
      ],
      provider_code: "evenbet_gaming",
    },
    {
      name: "CQ9",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1136,
      sort: 0,
      isAllowed: false,
      aliases: ["cq9"],
      provider_code: "cq9",
    },
    {
      name: "Coin Machine Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1139,
      sort: 0,
      isAllowed: false,
      aliases: [
        "coin-machine-gaming",
        "coin machine gaming",
        "coin_machine_gaming",
        "coinmachinegaming",
      ],
      provider_code: "coin_machine_gaming",
    },
    {
      name: "Darwin Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1141,
      sort: 0,
      isAllowed: false,
      aliases: ["DARWIN"],
      provider_code: "darwin_gaming",
    },
    {
      name: "Ethereal Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1143,
      sort: 0,
      isAllowed: false,
      aliases: [
        "ethereal gaming",
        "ethereal-gaming",
        "ethereal_gaming",
        "etherealgaming",
      ],
      provider_code: "ethereal_gaming",
    },
    {
      name: "Fat Panda",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1147,
      sort: 0,
      isAllowed: false,
      aliases: ["fat panda", "fatpanda", "fat_panda", "fat-panda"],
      provider_code: "fat_panda",
    },
    {
      name: "Foxium",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1149,
      sort: 0,
      isAllowed: false,
      aliases: ["foxium"],
      provider_code: "foxium",
    },
    {
      name: "Hölle Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1166,
      sort: 0,
      isAllowed: false,
      aliases: ["hölle_games", "hölle-games", "höllegames", "hölle games"],
      provider_code: "holle_games",
    },
    {
      name: "Pateplay",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1200,
      sort: 0,
      isAllowed: false,
      aliases: ["pateplay"],
      provider_code: "pateplay",
    },
    {
      name: "PlayHub",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1201,
      sort: 0,
      isAllowed: false,
      aliases: ["playhub"],
      provider_code: "playhub",
    },
    {
      name: "Spinlogic Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1223,
      sort: 0,
      isAllowed: false,
      aliases: [
        "spinlogic_gaming",
        "spinlogic-gaming",
        "spinlogicgaming",
        "spinlogic gaming",
      ],
      provider_code: "spinlogic_gaming",
    },
    {
      name: "St8",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1224,
      sort: 0,
      isAllowed: false,
      aliases: ["st8"],
      provider_code: "st8",
    },
    {
      name: "iMoon Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1243,
      sort: 0,
      isAllowed: false,
      aliases: ["imoongames", "imoon-games", "imoon games", "imoon_games"],
      provider_code: "imoon_games",
    },
    {
      name: "ELK Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1022,
      sort: 0,
      isAllowed: false,
      aliases: ["elk", "elk studios"],
      provider_code: "elk_studios",
    },
    {
      name: "GameArt",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1039,
      sort: 0,
      isAllowed: false,
      aliases: ["gameart"],
      provider_code: "gameart",
    },
    {
      name: "Swintt",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1045,
      sort: 0,
      isAllowed: false,
      aliases: ["swintt"],
      provider_code: "swintt",
    },
    {
      name: "Golden Hero",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1055,
      sort: 0,
      isAllowed: false,
      aliases: ["golden hero", "golden_hero", "goldenhero", "golden-hero"],
      provider_code: "golden_hero",
    },
    {
      name: "Apollo Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1078,
      sort: 0,
      isAllowed: false,
      aliases: ["apollo_games", "apollo-games", "apollo games", "apollogames"],
      provider_code: "apollo_games",
    },
    {
      name: "Lady Luck Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1086,
      sort: 0,
      isAllowed: false,
      aliases: [
        "lady luck games",
        "ladyluckgames",
        "lady_luck_games",
        "lady-luck-games",
      ],
      provider_code: "lady_luck_games",
    },
    {
      name: "Turbo Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1090,
      sort: 0,
      isAllowed: false,
      aliases: ["TURBO"],
      provider_code: "turbo_games",
    },
    {
      name: "PopOK Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1091,
      sort: 0,
      isAllowed: false,
      aliases: ["popok-gaming", "popokgaming", "popok gaming", "popok_gaming"],
      provider_code: "popok_gaming",
    },
    {
      name: "Advant Play",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1111,
      sort: 0,
      isAllowed: false,
      aliases: ["advantplay", "advant-play", "advant_play", "advant play"],
      provider_code: "advant_play",
    },
    {
      name: "Betby",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1128,
      sort: 0,
      isAllowed: false,
      aliases: ["betby"],
      provider_code: "betby",
    },
    {
      name: "Booongo",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1132,
      sort: 0,
      isAllowed: false,
      aliases: ["booongo"],
      provider_code: "booongo",
    },
    {
      name: "Hungry Bear Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1165,
      sort: 0,
      isAllowed: false,
      aliases: [
        "hungry-bear-gaming",
        "hungry_bear_gaming",
        "hungrybeargaming",
        "hungry bear gaming",
      ],
      provider_code: "hungry_bear_gaming",
    },
    {
      name: "Naga Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1185,
      sort: 0,
      isAllowed: false,
      aliases: ["Naga Gaming"],
      provider_code: "naga_games",
    },
    {
      name: "Nolimit City",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1191,
      sort: 0,
      isAllowed: false,
      aliases: ["nolimit_city", "nolimit city", "nolimit-city", "nolimitcity"],
      provider_code: "nolimit_city",
    },
    {
      name: "Novomatic",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1192,
      sort: 0,
      isAllowed: false,
      aliases: ["novomatic"],
      provider_code: "novomatic",
    },
    {
      name: "NowNow Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1193,
      sort: 0,
      isAllowed: false,
      aliases: [
        "nownow_gaming",
        "nownowgaming",
        "nownow-gaming",
        "nownow gaming",
      ],
      provider_code: "nownow_gaming",
    },
    {
      name: "Oriental Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1197,
      sort: 0,
      isAllowed: false,
      aliases: [
        "oriental gaming",
        "orientalgaming",
        "oriental_gaming",
        "oriental-gaming",
      ],
      provider_code: "oriental_gaming",
    },
    {
      name: "Raw iGaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1208,
      sort: 0,
      isAllowed: false,
      aliases: ["raw igaming", "raw_igaming", "raw-igaming", "rawigaming"],
      provider_code: "raw_igaming",
    },
    {
      name: "Betsoft",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1008,
      sort: 0,
      isAllowed: true,
      aliases: ["bet soft", "betsoft gaming"],
      provider_code: "betsoft",
    },
    {
      name: "Gamomat",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1030,
      sort: 0,
      isAllowed: false,
      aliases: ["gamomat"],
      provider_code: "gamomat",
    },
    {
      name: "Spadegaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1042,
      sort: 0,
      isAllowed: false,
      aliases: ["spadegaming"],
      provider_code: "spadegaming",
    },
    {
      name: "Fazi Interactive",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1052,
      sort: 0,
      isAllowed: false,
      aliases: [
        "fazi_interactive",
        "fazi-interactive",
        "fazi interactive",
        "faziinteractive",
      ],
      provider_code: "fazi_interactive",
    },
    {
      name: "MrSlotty",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1097,
      sort: 0,
      isAllowed: false,
      aliases: ["mrslotty"],
      provider_code: "mrslotty",
    },
    {
      name: "Zillion Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1104,
      sort: 0,
      isAllowed: false,
      aliases: [
        "zillion-games",
        "zillion_games",
        "zilliongames",
        "zillion games",
      ],
      provider_code: "zillion_games",
    },
    {
      name: "3 Oaks Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1106,
      sort: 0,
      isAllowed: false,
      aliases: [
        "3oaksgaming",
        "3 oaks gaming",
        "3-oaks-gaming",
        "3_oaks_gaming",
      ],
      provider_code: "3_oaks_gaming",
    },
    {
      name: "4ThePlayer",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1107,
      sort: 0,
      isAllowed: false,
      aliases: ["4theplayer"],
      provider_code: "4theplayer",
    },
    {
      name: "AreaVegas Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1115,
      sort: 0,
      isAllowed: false,
      aliases: [
        "areavegas games",
        "areavegasgames",
        "areavegas-games",
        "areavegas_games",
      ],
      provider_code: "areavegas_games",
    },
    {
      name: "Backseat Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1122,
      sort: 0,
      isAllowed: false,
      aliases: [
        "backseat_gaming",
        "backseat gaming",
        "backseat-gaming",
        "backseatgaming",
      ],
      provider_code: "backseat_gaming",
    },
    {
      name: "Barbara Bang",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1125,
      sort: 0,
      isAllowed: false,
      aliases: ["barbara-bang", "barbara bang", "barbarabang", "barbara_bang"],
      provider_code: "barbara_bang",
    },
    {
      name: "GameVy",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1152,
      sort: 0,
      isAllowed: false,
      aliases: ["gamevy"],
      provider_code: "gamevy",
    },
    {
      name: "Gamebeat",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1153,
      sort: 0,
      isAllowed: false,
      aliases: ["gamebeat"],
      provider_code: "gamebeat",
    },
    {
      name: "Gold Coin Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1159,
      sort: 0,
      isAllowed: false,
      aliases: [
        "gold_coin_studios",
        "gold coin studios",
        "goldcoinstudios",
        "gold-coin-studios",
      ],
      provider_code: "gold_coin_studios",
    },
    {
      name: "Hot Rise Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1164,
      sort: 0,
      isAllowed: false,
      aliases: [
        "hotrisegames",
        "hot rise games",
        "hot_rise_games",
        "hot-rise-games",
      ],
      provider_code: "hot_rise_games",
    },
    {
      name: "Million Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1183,
      sort: 0,
      isAllowed: false,
      aliases: [
        "million games",
        "million_games",
        "million-games",
        "milliongames",
      ],
      provider_code: "million_games",
    },
    {
      name: "FIESTA777",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1255,
      sort: 0,
      isAllowed: false,
      aliases: ["fiesta777"],
      provider_code: "fiesta777",
    },
    {
      name: "RG",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1256,
      sort: 0,
      isAllowed: false,
      aliases: ["rg"],
      provider_code: "rg",
    },
    {
      name: "ORYX Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1058,
      sort: 0,
      isAllowed: false,
      aliases: ["oryxgaming", "oryx-gaming", "oryx gaming", "oryx_gaming"],
      provider_code: "oryx_gaming",
    },
    {
      name: "Triple Edge Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1071,
      sort: 0,
      isAllowed: false,
      aliases: [
        "triple_edge_studios",
        "tripleedgestudios",
        "triple edge studios",
        "triple-edge-studios",
      ],
      provider_code: "triple_edge_studios",
    },
    {
      name: "Northern Lights Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1073,
      sort: 0,
      isAllowed: false,
      aliases: [
        "northern-lights-gaming",
        "northern lights gaming",
        "northern_lights_gaming",
        "northernlightsgaming",
      ],
      provider_code: "northern_lights_gaming",
    },
    {
      name: "AvatarUX",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1118,
      sort: 0,
      isAllowed: false,
      aliases: ["avatarux"],
      provider_code: "avatarux",
    },
    {
      name: "Betsolutions",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1129,
      sort: 0,
      isAllowed: false,
      aliases: ["betsolutions"],
      provider_code: "betsolutions",
    },
    {
      name: "Mancala Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1180,
      sort: 0,
      isAllowed: false,
      aliases: [
        "mancalagaming",
        "mancala gaming",
        "mancala_gaming",
        "mancala-gaming",
      ],
      provider_code: "mancala_gaming",
    },
    {
      name: "Old Skool Studios",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1195,
      sort: 0,
      isAllowed: false,
      aliases: [
        "old-skool-studios",
        "oldskoolstudios",
        "old skool studios",
        "old_skool_studios",
      ],
      provider_code: "old_skool_studios",
    },
    {
      name: "Slotopia",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1218,
      sort: 0,
      isAllowed: false,
      aliases: ["slotopia"],
      provider_code: "slotopia",
    },
    {
      name: "Viva Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1234,
      sort: 0,
      isAllowed: false,
      aliases: ["viva games", "viva_games", "vivagames", "viva-games"],
      provider_code: "viva_games",
    },
    {
      name: "VoltEnt",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1235,
      sort: 0,
      isAllowed: false,
      aliases: ["voltent"],
      provider_code: "voltent",
    },
    {
      name: "Pragmatic Play Live",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1245,
      sort: 0,
      isAllowed: false,
      aliases: [
        "pragmatic-play-live",
        "pragmatic play live",
        "pragmaticplaylive",
        "pragmatic_play_live",
      ],
      provider_code: "pragmatic_play_live",
    },
    {
      name: "RICH88",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1260,
      sort: 0,
      isAllowed: false,
      aliases: ["rich88"],
      provider_code: "rich88",
    },
    {
      name: "Endorphina",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1033,
      sort: 0,
      isAllowed: false,
      aliases: ["endorphina"],
      provider_code: "endorphina",
    },
    {
      name: "Felix Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1083,
      sort: 0,
      isAllowed: false,
      aliases: ["felixgaming", "felix gaming", "felix-gaming", "felix_gaming"],
      provider_code: "felix_gaming",
    },
    {
      name: "Dragon Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1092,
      sort: 0,
      isAllowed: false,
      aliases: [
        "dragongaming",
        "dragon-gaming",
        "dragon_gaming",
        "dragon gaming",
      ],
      provider_code: "dragon_gaming",
    },
    {
      name: "Eurasian Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1101,
      sort: 0,
      isAllowed: false,
      aliases: [
        "eurasian-gaming",
        "eurasian_gaming",
        "eurasian gaming",
        "eurasiangaming",
      ],
      provider_code: "eurasian_gaming",
    },
    {
      name: "AE Sexy",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1109,
      sort: 0,
      isAllowed: false,
      aliases: ["aesexy", "ae-sexy", "ae_sexy", "ae sexy"],
      provider_code: "ae_sexy",
    },
    {
      name: "Bang Bang Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1124,
      sort: 0,
      isAllowed: false,
      aliases: [
        "bangbanggames",
        "bang-bang-games",
        "bang_bang_games",
        "bang bang games",
      ],
      provider_code: "bang_bang_games",
    },
    {
      name: "Gamzix",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1158,
      sort: 0,
      isAllowed: false,
      aliases: ["gamzix"],
      provider_code: "gamzix",
    },
    {
      name: "Raw iGaming Live",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1209,
      sort: 0,
      isAllowed: false,
      aliases: [
        "raw igaming live",
        "rawigaminglive",
        "raw-igaming-live",
        "raw_igaming_live",
      ],
      provider_code: "raw_igaming_live",
    },
    {
      name: "Reel Life Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1210,
      sort: 0,
      isAllowed: false,
      aliases: ["Reel Life Gaming"],
      provider_code: "reel_life_games",
    },
    {
      name: "Reflex Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1212,
      sort: 0,
      isAllowed: false,
      aliases: [
        "reflex gaming",
        "reflex-gaming",
        "reflex_gaming",
        "reflexgaming",
      ],
      provider_code: "reflex_gaming",
    },
    {
      name: "Twain Sport",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1233,
      sort: 0,
      isAllowed: false,
      aliases: ["twain-sport", "twainsport", "twain sport", "twain_sport"],
      provider_code: "twain_sport",
    },
    {
      name: "SEXYBCRT",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1264,
      sort: 0,
      isAllowed: false,
      aliases: ["sexybcrt"],
      provider_code: "sexybcrt",
    },
    {
      name: "N2Live",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1267,
      sort: 0,
      isAllowed: false,
      aliases: ["n2live"],
      provider_code: "n2live",
    },
    {
      name: "Yuvi Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1268,
      sort: 0,
      isAllowed: false,
      aliases: ["yuvi_games", "yuvi games", "yuvigames", "yuvi-games"],
      provider_code: "yuvi_games",
    },
    {
      name: "PASCAL",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1273,
      sort: 0,
      isAllowed: false,
      aliases: ["pascal"],
      provider_code: "pascal",
    },
    {
      name: "Virtuals",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1282,
      sort: 0,
      isAllowed: false,
      aliases: ["virtuals"],
      provider_code: "virtuals",
    },
    {
      name: "SportsBook",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1286,
      sort: 0,
      isAllowed: false,
      aliases: ["sportsbook"],
      provider_code: "sportsbook",
    },
    {
      name: "Macaw Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1277,
      sort: 0,
      isAllowed: false,
      aliases: ["MACAW"],
      provider_code: "macaw_gaming",
    },
    {
      name: "GAPLOBBY",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1284,
      sort: 0,
      isAllowed: false,
      aliases: ["gaplobby"],
      provider_code: "gaplobby",
    },
    {
      name: "AE",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1269,
      sort: 0,
      isAllowed: false,
      aliases: ["ae"],
      provider_code: "ae",
    },
    {
      name: "Royal Gaming Lobby",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1272,
      sort: 0,
      isAllowed: false,
      aliases: [
        "royal_gaming_lobby",
        "royal gaming lobby",
        "royalgaminglobby",
        "royal-gaming-lobby",
      ],
      provider_code: "royal_gaming_lobby",
    },
    {
      name: "SV388",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1265,
      sort: 0,
      isAllowed: false,
      aliases: ["sv388"],
      provider_code: "sv388",
    },
    {
      name: "SuperNowa",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1270,
      sort: 0,
      isAllowed: false,
      aliases: ["supernowa"],
      provider_code: "supernowa",
    },
    {
      name: "KINGMAKER",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1274,
      sort: 0,
      isAllowed: false,
      aliases: ["kingmaker"],
      provider_code: "kingmaker",
    },
    {
      name: "3Cherry",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1276,
      sort: 0,
      isAllowed: false,
      aliases: ["3cherry"],
      provider_code: "3cherry",
    },
    {
      name: "Nmatic",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1271,
      sort: 0,
      isAllowed: false,
      aliases: ["nmatic"],
      provider_code: "nmatic",
    },
    {
      name: "Yuvi Games Lobby",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1279,
      sort: 0,
      isAllowed: false,
      aliases: [
        "yuvi games lobby",
        "yuvi-games-lobby",
        "yuvigameslobby",
        "yuvi_games_lobby",
      ],
      provider_code: "yuvi_games_lobby",
    },
    {
      name: "Premium",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1275,
      sort: 0,
      isAllowed: false,
      aliases: ["premium"],
      provider_code: "premium",
    },
    {
      name: "LLG",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1283,
      sort: 0,
      isAllowed: false,
      aliases: ["llg"],
      provider_code: "llg",
    },
    {
      name: "VENUS",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1266,
      sort: 0,
      isAllowed: false,
      aliases: ["venus"],
      provider_code: "venus",
    },
    {
      name: "RT",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1280,
      sort: 0,
      isAllowed: false,
      aliases: ["rt"],
      provider_code: "rt",
    },
    {
      name: "LUDO",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1285,
      sort: 0,
      isAllowed: false,
      aliases: ["ludo"],
      provider_code: "ludo",
    },
    {
      name: "Exchange",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1278,
      sort: 0,
      isAllowed: false,
      aliases: ["exchange"],
      provider_code: "exchange",
    },
    {
      name: "amusnet",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1281,
      sort: 0,
      isAllowed: false,
      aliases: ["amusnet"],
      provider_code: "amusnet",
    },
    {
      name: "EA",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1287,
      sort: 0,
      isAllowed: false,
      aliases: ["ea"],
      provider_code: "ea",
    },
    {
      name: "Mini Crash",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 284,
      sort: 0,
      isAllowed: false,
      aliases: ["minicrash", "mini crash", "mini-crash", "mini_crash"],
      provider_code: "mini_crash",
    },
    {
      name: "Pinky Gaming",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 285,
      sort: 0,
      isAllowed: false,
      aliases: ["pinky-gaming", "pinky_gaming", "pinky gaming", "pinkygaming"],
      provider_code: "pinky_gaming",
    },
    {
      name: "NEOLOBBY",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 286,
      sort: 0,
      isAllowed: false,
      aliases: ["neolobby"],
      provider_code: "neolobby",
    },
    {
      name: "iSoftBet",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1288,
      sort: 0,
      isAllowed: true,
      aliases: ["isoftbet"],
      provider_code: "isoftbet",
      autoEnableNewGames: true,
    },
    {
      name: "Super Spade Games",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1289,
      sort: 0,
      isAllowed: true,
      aliases: [
        "super_spade_games",
        "super spade games",
        "superspadegames",
        "super-spade-games",
      ],
      provider_code: "super_spade_games",
      autoEnableNewGames: true,
    },
    {
      name: "Real Time Gaming (RTG)",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1290,
      sort: 0,
      isAllowed: true,
      aliases: [
        "real time gaming (rtg)",
        "real-time-gaming-rtg",
        "realtimegamingrtg",
        "real_time_gaming_rtg",
      ],
      provider_code: "real_time_gaming_rtg",
      autoEnableNewGames: true,
    },
    {
      name: "3OAKS",
      icon: null,
      restrictedAreas: [],
      isDeleted: false,
      id: 1291,
      sort: 0,
      isAllowed: false,
      aliases: ["3oaks"],
      provider_code: "3oaks",
      autoEnableNewGames: true,
      maintenanceEndUTC: null,
      maintenanceStartUTC: null,
    },
];

const seed = async () => {
  try {
    await connectDB();
    await Provider.deleteMany({});
    await Provider.insertMany(data);
    logger.info("seed.providers.success", { count: data.length });
  } catch (error) {
    logger.error("seed.providers.failure", { error });
  }
};

if (require.main === module) {
  seed();
}

module.exports = { seed };
