module.exports = {
  NetEnt: ["netent", "net", "net ent", "net-ent"],
  "Pragmatic Play": [
    "PG",
    "pragmatic",
    "pragmatic play",
    "pragmaticplay",
    "pragmatic_play",
  ],
  "Play'n GO": ["playngo", "play n go", "playn go", "png", "Play'n Go"],
  Microgaming: ["mg", "micro", "micro gaming"],
  Betsoft: ["bet soft", "betsoft gaming"],
  Yggdrasil: ["ygg", "yggdrasil gaming"],
  "Red Tiger": ["redtiger", "red tiger gaming"],
  "Big Time Gaming": [
    "big time gaming",
    "bigtimegaming",
    "big_time_gaming",
    "big-time-gaming",
  ],
  Quickspin: ["qs", "quick spin"],
  Ezugi: ["ezg", "ez"],
  "Authentic Gaming": [
    "authentic gaming",
    "authentic-gaming",
    "authentic_gaming",
    "authenticgaming",
  ],
  "OnAir Entertainment": [
    "onair_entertainment",
    "onair-entertainment",
    "onair entertainment",
    "onairentertainment",
  ],
  "Vivo Gaming": ["Vivo Games"],
  "Asia Gaming": ["asia gaming", "asia_gaming", "asia-gaming", "asiagaming"],
  "Hacksaw Gaming": [
    "hacksawgaming",
    "hacksaw-gaming",
    "hacksaw_gaming",
    "hacksaw gaming",
  ],
  "Push Gaming": ["push", "pushgaming"],
  "Relax Gaming": ["relax", "relaxgaming"],
  "NoLimit City": ["nolimit", "nlc"],
  "ELK Studios": ["elk", "elk studios"],
  "Blueprint Gaming": ["blueprint", "bpg"],
  Thunderkick: ["tk", "thunder kick"],
  Wazdan: ["wzd", "wazdan gaming"],
  "Kalamba Games": [
    "kalamba-games",
    "kalambagames",
    "kalamba games",
    "kalamba_games",
  ],
  Spinomenal: ["spinomenal"],
  "SoftSwiss (BGaming)": [
    "softswiss_bgaming",
    "softswiss-bgaming",
    "softswiss (bgaming)",
    "softswissbgaming",
  ],
  "Amatic Industries": [
    "amatic_industries",
    "amaticindustries",
    "amatic-industries",
    "amatic industries",
  ],
  Gamomat: ["gamomat"],
  Playson: ["playson"],
  Pariplay: ["pariplay"],
  Endorphina: ["endorphina"],
  "Booming Games": [
    "booming_games",
    "boominggames",
    "booming games",
    "booming-games",
  ],
  "Belatra Games": [
    "belatragames",
    "belatra games",
    "belatra_games",
    "belatra-games",
  ],
  "Mascot Gaming": [
    "mascot gaming",
    "mascot_gaming",
    "mascot-gaming",
    "mascotgaming",
  ],
  "1x2gaming": ["1x2gaming"],
  "Iron Dog Studio": [
    "iron-dog-studio",
    "irondogstudio",
    "iron_dog_studio",
    "iron dog studio",
  ],
  GameArt: ["gameart"],
  Fugaso: ["fugaso"],
  "Tom Horn Gaming": [
    "tomhorngaming",
    "tom_horn_gaming",
    "tom-horn-gaming",
    "tom horn gaming",
  ],
  Spadegaming: ["spadegaming"],
  Slotmill: ["slotmill"],
  "Peter & Sons": [
    "peterandsons",
    "peter-and-sons",
    "peter_and_sons",
    "peter & sons",
  ],
  Swintt: ["swintt"],
  ReelPlay: ["reelplay"],
  "Stormcraft Studios": [
    "stormcraft studios",
    "stormcraftstudios",
    "stormcraft-studios",
    "stormcraft_studios",
  ],
  LuckyStreak: ["luckystreak"],
  BetGames: ["BETGAMES"],
  Digitain: ["digitain"],
  "Fazi Interactive": [
    "fazi_interactive",
    "fazi-interactive",
    "fazi interactive",
    "faziinteractive",
  ],
  "Spearhead Studios": [
    "spearhead_studios",
    "spearhead studios",
    "spearheadstudios",
    "spearhead-studios",
  ],
  "All41 Studios": [
    "all41-studios",
    "all41_studios",
    "all41studios",
    "all41 studios",
  ],
  "Golden Hero": ["golden hero", "golden_hero", "goldenhero", "golden-hero"],
  "Leap Gaming": ["leap_gaming", "leap-gaming", "leapgaming", "leap gaming"],
  "Green Jade Games": [
    "green_jade_games",
    "green jade games",
    "greenjadegames",
    "green-jade-games",
  ],
  "ORYX Gaming": ["oryxgaming", "oryx-gaming", "oryx gaming", "oryx_gaming"],
  Spinmatic: ["spinmatic"],
  "Skywind Group": [
    "skywind group",
    "skywind_group",
    "skywindgroup",
    "skywind-group",
  ],
  "Wizard Games": [
    "wizardgames",
    "wizard games",
    "wizard-games",
    "wizard_games",
  ],
  "BF Games": ["bfgames", "bf-games", "bf games", "bf_games"],
  "Givme Games": ["givmegames", "givme games", "givme-games", "givme_games"],
  "Fantasma Games": [
    "fantasma-games",
    "fantasma games",
    "fantasma_games",
    "fantasmagames",
  ],
  "August Gaming": [
    "august gaming",
    "augustgaming",
    "august-gaming",
    "august_gaming",
  ],
  "7Mojos": ["7mojos"],
  Betixon: ["betixon"],
  "Casino Technology": [
    "casinotechnology",
    "casino technology",
    "casino-technology",
    "casino_technology",
  ],
  "CQ9 Gaming": ["cq9-gaming", "cq9_gaming", "cq9 gaming", "cq9gaming"],
  "Red Rake Gaming": [
    "red rake gaming",
    "red-rake-gaming",
    "red_rake_gaming",
    "redrakegaming",
  ],
  "Triple Edge Studios": [
    "triple_edge_studios",
    "tripleedgestudios",
    "triple edge studios",
    "triple-edge-studios",
  ],
  "Slingshot Studios": [
    "slingshot-studios",
    "slingshot_studios",
    "slingshot studios",
    "slingshotstudios",
  ],
  "Northern Lights Gaming": [
    "northern-lights-gaming",
    "northern lights gaming",
    "northern_lights_gaming",
    "northernlightsgaming",
  ],
  "Just For The Win (JFTW)": [
    "just_for_the_win_jftw",
    "justforthewinjftw",
    "just for the win (jftw)",
    "just-for-the-win-jftw",
  ],
  "Lightning Box": [
    "lightning-box",
    "lightningbox",
    "lightning_box",
    "lightning box",
  ],
  "PearFiction Studios": [
    "pearfictionstudios",
    "pearfiction studios",
    "pearfiction-studios",
    "pearfiction_studios",
  ],
  "Pearl Abyss": ["pearlabyss", "pearl-abyss", "pearl_abyss", "pearl abyss"],
  "Apollo Games": [
    "apollo_games",
    "apollo-games",
    "apollo games",
    "apollogames",
  ],
  "Maverick Slots": [
    "maverickslots",
    "maverick-slots",
    "maverick_slots",
    "maverick slots",
  ],
  "Real Dealer Studios": [
    "real dealer studios",
    "realdealerstudios",
    "real_dealer_studios",
    "real-dealer-studios",
  ],
  "SmartSoft Gaming": [
    "smartsoft_gaming",
    "smartsoftgaming",
    "smartsoft gaming",
    "smartsoft-gaming",
  ],
  OneTouch: ["onetouch"],
  "Felix Gaming": [
    "felixgaming",
    "felix gaming",
    "felix-gaming",
    "felix_gaming",
  ],
  "Games Inc": ["games_inc", "games inc", "gamesinc", "games-inc"],
  "Synot Games": ["synot-games", "synot games", "synotgames", "synot_games"],
  "Lady Luck Games": [
    "lady luck games",
    "ladyluckgames",
    "lady_luck_games",
    "lady-luck-games",
  ],
  Arcadem: ["arcadem"],
  Onlyplay: ["onlyplay"],
  Spribe: ["SPRIBE"],
  "Turbo Games": ["TURBO"],
  "PopOK Gaming": [
    "popok-gaming",
    "popokgaming",
    "popok gaming",
    "popok_gaming",
  ],
  "Dragon Gaming": [
    "dragongaming",
    "dragon-gaming",
    "dragon_gaming",
    "dragon gaming",
  ],
  "Lucky Elektra": [
    "lucky-elektra",
    "luckyelektra",
    "lucky_elektra",
    "lucky elektra",
  ],
  "InBet Games": ["inbet-games", "inbet_games", "inbetgames", "inbet games"],
  BGaming: ["bgaming"],
  "KA Gaming": ["ka_gaming", "kagaming", "ka-gaming", "ka gaming"],
  MrSlotty: ["mrslotty"],
  "Nucleus Gaming": [
    "nucleusgaming",
    "nucleus-gaming",
    "nucleus gaming",
    "nucleus_gaming",
  ],
  WorldMatch: ["worldmatch"],
  "EvenBet Gaming": [
    "evenbet_gaming",
    "evenbet gaming",
    "evenbet-gaming",
    "evenbetgaming",
  ],
  "Eurasian Gaming": [
    "eurasian-gaming",
    "eurasian_gaming",
    "eurasian gaming",
    "eurasiangaming",
  ],
  "Jili Gaming": ["JiLi Gaming"],
  "CT Interactive": [
    "ct interactive",
    "ct_interactive",
    "ctinteractive",
    "ct-interactive",
  ],
  "Zillion Games": [
    "zillion-games",
    "zillion_games",
    "zilliongames",
    "zillion games",
  ],
  "1Spin4Win": ["1spin4win"],
  "3 Oaks Gaming": [
    "3oaksgaming",
    "3 oaks gaming",
    "3-oaks-gaming",
    "3_oaks_gaming",
  ],
  "4ThePlayer": ["4theplayer"],
  "9 Wickets": ["9_wickets", "9wickets", "9-wickets", "9 wickets"],
  "AE Sexy": ["aesexy", "ae-sexy", "ae_sexy", "ae sexy"],
  "Ace Roll": ["ace_roll", "ace roll", "ace-roll", "aceroll"],
  "Advant Play": ["advantplay", "advant-play", "advant_play", "advant play"],
  "Alchemy Gaming": [
    "alchemygaming",
    "alchemy_gaming",
    "alchemy-gaming",
    "alchemy gaming",
  ],
  "All For One Studios": [
    "allforonestudios",
    "all-for-one-studios",
    "all_for_one_studios",
    "all for one studios",
  ],
  "Amigo Gaming": [
    "amigo-gaming",
    "amigogaming",
    "amigo gaming",
    "amigo_gaming",
  ],
  "AreaVegas Games": [
    "areavegas games",
    "areavegasgames",
    "areavegas-games",
    "areavegas_games",
  ],
  "Aura Gaming": ["auragaming", "aura gaming", "aura-gaming", "aura_gaming"],
  "Aurum Signature Studios": [
    "aurum signature studios",
    "aurum_signature_studios",
    "aurum-signature-studios",
    "aurumsignaturestudios",
  ],
  AvatarUX: ["avatarux"],
  Aviator: ["aviator"],
  Aviatrix: ["aviatrix"],
  BTi: ["bti"],
  "Backseat Gaming": [
    "backseat_gaming",
    "backseat gaming",
    "backseat-gaming",
    "backseatgaming",
  ],
  "Bad Dingo": ["bad_dingo", "bad dingo", "baddingo", "bad-dingo"],
  "Bang Bang Games": [
    "bangbanggames",
    "bang-bang-games",
    "bang_bang_games",
    "bang bang games",
  ],
  "Barbara Bang": [
    "barbara-bang",
    "barbara bang",
    "barbarabang",
    "barbara_bang",
  ],
  Barstruck: ["barstruck"],
  "BetGames Live": [
    "betgames-live",
    "betgameslive",
    "betgames_live",
    "betgames live",
  ],
  Betby: ["betby"],
  Betsolutions: ["betsolutions"],
  "Blue Ring Studios": [
    "blueringstudios",
    "blue-ring-studios",
    "blue ring studios",
    "blue_ring_studios",
  ],
  "Boomerang Studios": ["Boomerang"],
  Booongo: ["booongo"],
  "Buck Stakes Entertainment": [
    "buck-stakes-entertainment",
    "buck_stakes_entertainment",
    "buck stakes entertainment",
    "buckstakesentertainment",
  ],
  "Bulletproof Games": [
    "bulletproof games",
    "bulletproof-games",
    "bulletproofgames",
    "bulletproof_games",
  ],
  "Bullshark Games": [
    "bullshark games",
    "bullsharkgames",
    "bullshark_games",
    "bullshark-games",
  ],
  CQ9: ["cq9"],
  Charismatic: ["charismatic"],
  "Circular Arrow": [
    "circular-arrow",
    "circular arrow",
    "circular_arrow",
    "circulararrow",
  ],
  "Coin Machine Gaming": [
    "coin-machine-gaming",
    "coin machine gaming",
    "coin_machine_gaming",
    "coinmachinegaming",
  ],
  "Crazy Tooth Studio": [
    "crazy tooth studio",
    "crazy-tooth-studio",
    "crazytoothstudio",
    "crazy_tooth_studio",
  ],
  "Darwin Gaming": ["DARWIN"],
  "Elysium Studios": [
    "elysium-studios",
    "elysium studios",
    "elysiumstudios",
    "elysium_studios",
  ],
  "Ethereal Gaming": [
    "ethereal gaming",
    "ethereal-gaming",
    "ethereal_gaming",
    "etherealgaming",
  ],
  "Eurostar Studios": [
    "eurostar-studios",
    "eurostar studios",
    "eurostar_studios",
    "eurostarstudios",
  ],
  "Evoplay Entertainment": [
    "evoplay entertainment",
    "evoplayentertainment",
    "evoplay_entertainment",
    "evoplay-entertainment",
  ],
  "Fa Chai": ["fa-chai", "fa_chai", "fa chai", "fachai"],
  "Fat Panda": ["fat panda", "fatpanda", "fat_panda", "fat-panda"],
  "Fortune Factory Studios": [
    "fortune_factory_studios",
    "fortunefactorystudios",
    "fortune factory studios",
    "fortune-factory-studios",
  ],
  Foxium: ["foxium"],
  "Gacha Studios": [
    "gacha_studios",
    "gachastudios",
    "gacha-studios",
    "gacha studios",
  ],
  Gambit: ["gambit"],
  GameVy: ["gamevy"],
  Gamebeat: ["gamebeat"],
  "Gameburger Studios": [
    "gameburger_studios",
    "gameburger-studios",
    "gameburger studios",
    "gameburgerstudios",
  ],
  "Games Global": [
    "games global",
    "gamesglobal",
    "games_global",
    "games-global",
  ],
  "Gaming Corps": [
    "gaming corps",
    "gamingcorps",
    "gaming-corps",
    "gaming_corps",
  ],
  "Gaming Realms": [
    "gaming-realms",
    "gaming realms",
    "gaming_realms",
    "gamingrealms",
  ],
  Gamzix: ["gamzix"],
  "Gold Coin Studios": [
    "gold_coin_studios",
    "gold coin studios",
    "goldcoinstudios",
    "gold-coin-studios",
  ],
  "Gong Gaming": ["gong_gaming", "gong gaming", "gonggaming", "gong-gaming"],
  "Half Pixel Studios": [
    "half-pixel-studios",
    "half pixel studios",
    "halfpixelstudios",
    "half_pixel_studios",
  ],
  "Hammertime Games": [
    "hammertime-games",
    "hammertime_games",
    "hammertimegames",
    "hammertime games",
  ],
  "High Limit Studios": [
    "high limit studios",
    "high_limit_studios",
    "highlimitstudios",
    "high-limit-studios",
  ],
  "Hot Rise Games": [
    "hotrisegames",
    "hot rise games",
    "hot_rise_games",
    "hot-rise-games",
  ],
  "Hungry Bear Gaming": [
    "hungry-bear-gaming",
    "hungry_bear_gaming",
    "hungrybeargaming",
    "hungry bear gaming",
  ],
  "H\u00f6lle Games": [
    "h\u00f6lle_games",
    "h\u00f6lle-games",
    "h\u00f6llegames",
    "h\u00f6lle games",
  ],
  ICONIC21: ["iconic21"],
  "INO Games": ["inogames", "ino_games", "ino-games", "ino games"],
  "InOut Games": ["inoutgames", "inout-games", "inout_games", "inout games"],
  "Infinity Dragon Studios": [
    "infinity dragon studios",
    "infinitydragonstudios",
    "infinity_dragon_studios",
    "infinity-dragon-studios",
  ],
  JDB: ["jdb"],
  "Jade Rabbit Studio": [
    "jade-rabbit-studio",
    "jade rabbit studio",
    "jade_rabbit_studio",
    "jaderabbitstudio",
  ],
  Jelly: ["jelly"],
  "Just For The Win Studios": [
    "just for the win studios",
    "just_for_the_win_studios",
    "just-for-the-win-studios",
    "justforthewinstudios",
  ],
  Kingmidas: ["kingmidas"],
  "Kiron Interactive": [
    "kironinteractive",
    "kiron-interactive",
    "kiron interactive",
    "kiron_interactive",
  ],
  "Kitsune Studios": [
    "kitsune_studios",
    "kitsunestudios",
    "kitsune-studios",
    "kitsune studios",
  ],
  "Lambda Gaming": [
    "lambda-gaming",
    "lambdagaming",
    "lambda_gaming",
    "lambda gaming",
  ],
  "Leander Games": [
    "leander-games",
    "leandergames",
    "leander games",
    "leander_games",
  ],
  "Mancala Gaming": [
    "mancalagaming",
    "mancala gaming",
    "mancala_gaming",
    "mancala-gaming",
  ],
  "Manna Play": ["manna-play", "mannaplay", "manna play", "manna_play"],
  MegaFUNalo: ["megafunalo"],
  "Million Games": [
    "million games",
    "million_games",
    "million-games",
    "milliongames",
  ],
  Mobilots: ["mobilots"],
  "Naga Games": ["Naga Gaming"],
  "Nailed It! Games": [
    "nailed_it!_games",
    "nailedit!games",
    "nailed it! games",
    "nailed-it!-games",
  ],
  "Neko Games": ["neko_games", "neko-games", "nekogames", "neko games"],
  "Neon Valley Studios": [
    "neon_valley_studios",
    "neonvalleystudios",
    "neon valley studios",
    "neon-valley-studios",
  ],
  "NetGame Entertainment": [
    "netgame_entertainment",
    "netgame entertainment",
    "netgameentertainment",
    "netgame-entertainment",
  ],
  NetGaming: ["netgaming"],
  "Nolimit City": [
    "nolimit_city",
    "nolimit city",
    "nolimit-city",
    "nolimitcity",
  ],
  Novomatic: ["novomatic"],
  "NowNow Gaming": [
    "nownow_gaming",
    "nownowgaming",
    "nownow-gaming",
    "nownow gaming",
  ],
  Octoplay: ["octoplay"],
  "Old Skool Studios": [
    "old-skool-studios",
    "oldskoolstudios",
    "old skool studios",
    "old_skool_studios",
  ],
  OneGame: ["onegame"],
  "Oriental Gaming": [
    "oriental gaming",
    "orientalgaming",
    "oriental_gaming",
    "oriental-gaming",
  ],
  "Oros Gaming": ["oros gaming", "oros_gaming", "orosgaming", "oros-gaming"],
  "PHOENIX 7": ["phoenix7", "phoenix_7", "phoenix 7", "phoenix-7"],
  Pateplay: ["pateplay"],
  PlayHub: ["playhub"],
  Playzia: ["playzia"],
  Popiplay: ["popiplay"],
  "Print Studios": [
    "print studios",
    "print-studios",
    "printstudios",
    "print_studios",
  ],
  "Qubit Games": ["qubit-games", "qubit_games", "qubitgames", "qubit games"],
  "RTG Slots": ["rtg_slots", "rtgslots", "rtg-slots", "rtg slots"],
  "Rabcat Gambling": ["Rabcat"],
  "Raw iGaming": ["raw igaming", "raw_igaming", "raw-igaming", "rawigaming"],
  "Raw iGaming Live": [
    "raw igaming live",
    "rawigaminglive",
    "raw-igaming-live",
    "raw_igaming_live",
  ],
  "Reel Life Games": ["Reel Life Gaming"],
  Reevo: ["reevo"],
  "Reflex Gaming": [
    "reflex gaming",
    "reflex-gaming",
    "reflex_gaming",
    "reflexgaming",
  ],
  "Royal Gaming": [
    "royal_gaming",
    "royal gaming",
    "royalgaming",
    "royal-gaming",
  ],
  "SA Gaming": ["sa gaming", "sa-gaming", "sa_gaming", "sagaming"],
  "Saba Sports": ["SABA"],
  Sap: ["sap"],
  "Shady Lady": ["shady_lady", "shadylady", "shady lady", "shady-lady"],
  Slotopia: ["slotopia"],
  "Smartsoft Gaming": [
    "smartsoft_gaming",
    "smartsoftgaming",
    "smartsoft gaming",
    "smartsoft-gaming",
  ],
  "Snowborn Games": [
    "snowborn_games",
    "snowborn-games",
    "snowborn games",
    "snowborngames",
  ],
  SpinOro: ["spinoro"],
  "SpinPlay Games": [
    "spinplaygames",
    "spinplay games",
    "spinplay-games",
    "spinplay_games",
  ],
  "Spinlogic Gaming": [
    "spinlogic_gaming",
    "spinlogic-gaming",
    "spinlogicgaming",
    "spinlogic gaming",
  ],
  St8: ["st8"],
  "Swintt Games": [
    "swinttgames",
    "swintt_games",
    "swintt-games",
    "swintt games",
  ],
  "Swintt Premium": [
    "swinttpremium",
    "swintt-premium",
    "swintt_premium",
    "swintt premium",
  ],
  "Switch Studios": [
    "switch studios",
    "switchstudios",
    "switch_studios",
    "switch-studios",
  ],
  TVBet: ["TVBET", "tvbet"],
  "TaDa Gaming": ["tada-gaming", "tadagaming", "tada gaming", "tada_gaming"],
  "Tequity Originals": [
    "tequity_originals",
    "tequityoriginals",
    "tequity originals",
    "tequity-originals",
  ],
  "Top Spin": ["topspin", "top-spin", "top spin", "top_spin"],
  "Trusty Studios": [
    "trusty-studios",
    "trusty studios",
    "trustystudios",
    "trusty_studios",
  ],
  "Twain Sport": ["twain-sport", "twainsport", "twain sport", "twain_sport"],
  "Viva Games": ["viva games", "viva_games", "vivagames", "viva-games"],
  VoltEnt: ["voltent"],
  "Wicked Games": [
    "wicked games",
    "wickedgames",
    "wicked_games",
    "wicked-games",
  ],
  "Win Fast Games": [
    "win fast games",
    "winfastgames",
    "win-fast-games",
    "win_fast_games",
  ],
  Winfinity: ["winfinity"],
  Winspinity: ["winspinity"],
  Wishbone: ["wishbone"],
  "Yellow Bat Gaming": [
    "yellow bat gaming",
    "yellowbatgaming",
    "yellow-bat-gaming",
    "yellow_bat_gaming",
  ],
  Yolted: ["yolted"],
  "iMoon Games": ["imoongames", "imoon-games", "imoon games", "imoon_games"],
  "Evolution Gaming": ["Evolution"],
  "Pragmatic Play Live": [
    "pragmatic-play-live",
    "pragmatic play live",
    "pragmaticplaylive",
    "pragmatic_play_live",
  ],
  Habanero: ["habanero"],
  Playtech: ["playtech"],
  "Playtech Live": [
    "playtech_live",
    "playtechlive",
    "playtech-live",
    "playtech live",
  ],
  PGSoft: ["pgsoft"],
  RubyPlay: ["rubyplay"],
  FIESTA777: ["fiesta777"],
  MARBLES: ["Marbles"],
  RG: ["rg"],
  HORSEBOOK: ["horsebook"],
  RICH88: ["rich88"],
  POPOK: ["PopOk"],
  CREED: ["creed"],
  "Royal Gaming Virtual": [
    "royal-gaming-virtual",
    "royal gaming virtual",
    "royalgamingvirtual",
    "royal_gaming_virtual",
  ],
  SEXYBCRT: ["sexybcrt"],
  SV388: ["sv388"],
  VENUS: ["venus"],
  N2Live: ["n2live"],
  "Yuvi Games": ["yuvi_games", "yuvi games", "yuvigames", "yuvi-games"],
  AE: ["ae"],
  SuperNowa: ["supernowa"],
  Nmatic: ["nmatic"],
  "Royal Gaming Lobby": [
    "royal_gaming_lobby",
    "royal gaming lobby",
    "royalgaminglobby",
    "royal-gaming-lobby",
  ],
  PASCAL: ["pascal"],
  KINGMAKER: ["kingmaker"],
  Premium: ["premium"],
  "3Cherry": ["3cherry"],
  "Macaw Gaming": ["MACAW"],
  Exchange: ["exchange"],
  "Yuvi Games Lobby": [
    "yuvi games lobby",
    "yuvi-games-lobby",
    "yuvigameslobby",
    "yuvi_games_lobby",
  ],
  RT: ["rt"],
  amusnet: ["amusnet"],
  Virtuals: ["virtuals"],
  LLG: ["llg"],
  GAPLOBBY: ["gaplobby"],
  LUDO: ["ludo"],
  SportsBook: ["sportsbook"],
  EA: ["ea"],
  "Mini Crash": ["minicrash", "mini crash", "mini-crash", "mini_crash"],
  "Pinky Gaming": [
    "pinky-gaming",
    "pinky_gaming",
    "pinky gaming",
    "pinkygaming",
  ],
  NEOLOBBY: ["neolobby"],
  iSoftBet: ["isoftbet"],
  "Super Spade Games": [
    "super_spade_games",
    "super spade games",
    "superspadegames",
    "super-spade-games",
  ],
  "Real Time Gaming (RTG)": [
    "real time gaming (rtg)",
    "real-time-gaming-rtg",
    "realtimegamingrtg",
    "real_time_gaming_rtg",
  ],
  "3OAKS": ["3oaks"],
};
