export enum GAME_REMOVAL_STATUS {
  NOT_DELETED = 0,
  DELETED_BY_PROVIDER = 1,
  DELETED_BY_US = 2,
}

export const GAME_STATUS = {
  ENABLED_BY_ADMIN: 'ACTIVE',
  DISABLED: 'DISABLED',
  DISABLED_BY_ADMIN: 'DISABLED BY ADMIN',
  ENABLED_BY_PROVIDER: 'ACTIVE',
  DISABLED_PROVIDER_BY_ADMIN: 'DISABLED',
  DISABLED_BY_PROVIDER: 'DISABLED BY PROVIDER',
};

export const GAME_CATEGORY_VISIBILITY = {
  VISIBLE: 'VISIBLE',
  NOT_VISIBLE: 'NOT VISIBLE',
};
